### ISSUE TITLE
준크에게 코드 전송

### ISSUE THREAD

**Issue by leedhm88** [Soccjs/butter#12]

**Comment by leedhm88** [comment]
$(".left_editor").droppable(
   {
      drop: function ()
      {

```
  }
```

   });

   // XML parser
   function makeParser()
   {
      var xml = $(".right_editor").text().replace(/\"/g,"'");
      var   xmlDoc = $.parseXML(xml);
      $xml = $(xmlDoc);

```
  var fullHtml = makeChildeNode(xmlDoc);
  $("#left_editor").html(fullHtml);

  makeDraggableAndResizable();
  /*dpi_x = document.getElementById('testdiv').offsetWidth;
     dpi_y = document.getElementById('testdiv').offsetHeight;*/
```

   }

   // set Draggable Event and Resizable Event
   function makeDraggableAndResizable()
   {
      setEvent(".TextView");
      setEvent(".Button");
      setEvent(".inputType");
      setEvent(".RadioButton");
      setEvent(".CheckBox");
      setEvent(".WebView");
      setEvent(".ImageView");
      setEvent(".ScrollView");
      setEvent(".LinearLayout");
      setEvent(".RelativeLayout");
      setEvent(".FrameLayout");
   }

   function setEvent(type)
   {
      $(type).draggable({containment:"#left_editor",scroll:false})
      .resizable({maxHeight: 600,maxWidth: 560,minHeight: 300,minWidth: 500,containment:"#left_editor" , autoHide:true, handles:"n,e,s,w"  });
   }

**Comment by leedhm88** [comment]
function makeInputTypeView(xml, type)
   {
      //DIV생성
      var viewHTML = "<div class=\"inputType\" ";

**Comment by Jay-devhub** [comment]
머여 , 이거 제목내용보면, 기존양식을 지키지 않음
