### ISSUE TITLE
형준이형선물

### ISSUE THREAD

**Issue by Soccjs** [Soccjs/butter#33]

**Comment by Jay-devhub** [comment]
이건 뭐죠

**Comment by p22ju** [comment]
모죵쓰

**Comment by Soccjs** [comment]
아이켐테스트

**Comment by Soccjs** [comment]
xml="http://schemas.android.com/apk/res/android"

**Comment by Jay-devhub** [comment]
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
android:id="@+id/linearlayout0"
android:layout_width="wrap_content"
android:layout_height="wrap_content"
android:orientation="vertical"

> <TextView android:id="@+id/textview0"
> android:layout_width="wrap_content"
> android:layout_height="wrap_content"
> android:text="TextView"
> />

</LinearLayout>
