### ISSUE TITLE
[graphical layout] 준석돕기 - lee

### ISSUE THREAD

**Issue by Soccjs** [Soccjs/butter#6]
준석이를 돕자!

**Comment by leedhm88** [comment]
// TextView 속성 추출
   function makeTextView(xml)
   {
      //DIV생성
      var viewHTML = "<div ";
      //ID생성
      viewHTML += getId(xml);
      //DIV STYLE생성
      viewHTML += "style=\"background-color:#FFF;"+defaultOrientation;
      //SPAN 기본 Default View 속성 생성
      viewHTML += makeDefaultView(xml);
      //END STYLE생성
      viewHTML += "\" ";
      //TextView Class 생성
      viewHTML += setClass("TextView");
      //END DIV생성
      viewHTML += ">";
      //SPAN CLASS생성
      viewHTML += "<span>";
      //TEXT생성:텍스트는 가장 마지막에 추가 하고 종료한다.
      viewHTML += getText(xml)+"</span></div>";
      return viewHTML;
   }

// 기본 View 속성 추출
   function makeDefaultView(xml)
   {
      var viewHTML = "";
      //WIDTH생성
      viewHTML += getWidth(xml);
      //HEIGHT생성
      viewHTML += getHeight(xml);
      //MARGIN생성
      viewHTML += getMargin(xml);
      //RELATIVE MARGIN생성
      viewHTML += getRelativeMargin(xml);
      //TEXTSIZE생성
      viewHTML += getTextSize(xml);
      //TEXTSTYLE생성
      viewHTML += getTextStyle(xml);
      //TEXTCOLOR생성
      viewHTML += getTextColor(xml);
      //TEXT생성
      viewHTML += getText(xml);
      //GRAVITY생성
      viewHTML += getGravity(xml);
      //ELLIPSIZE생성
      viewHTML += getEllipsize(xml);
      //BACKGROUND생성
      viewHTML += getBackground(xml);
      return viewHTML;
   }

**Comment by leedhm88** [comment]
// TextView 속성 추출
   function makeTextView(xml)
   {
      //DIV생성
      var viewHTML = "<div ";
      //ID생성
      viewHTML += getId(xml);
      //DIV STYLE생성
      viewHTML += "style=\"background-color:#FFF;"+defaultOrientation;
      //SPAN 기본 Default View 속성 생성
      viewHTML += makeDefaultView(xml);
      //END STYLE생성
      viewHTML += "\" ";
      //TextView Class 생성
      viewHTML += setClass("TextView");
      //END DIV생성
      viewHTML += ">";
      //SPAN CLASS생성
      viewHTML += "<span>";
      //TEXT생성:텍스트는 가장 마지막에 추가 하고 종료한다.
      viewHTML += getText(xml)+"</span></div>";
      return viewHTML;
   }

// 기본 View 속성 추출
   function makeDefaultView(xml)
   {
      var viewHTML = "";
      //WIDTH생성
      viewHTML += getWidth(xml);
      //HEIGHT생성
      viewHTML += getHeight(xml);
      //MARGIN생성
      viewHTML += getMargin(xml);
      //RELATIVE MARGIN생성
      viewHTML += getRelativeMargin(xml);
      //TEXTSIZE생성
      viewHTML += getTextSize(xml);
      //TEXTSTYLE생성
      viewHTML += getTextStyle(xml);
      //TEXTCOLOR생성
      viewHTML += getTextColor(xml);
      //TEXT생성
      viewHTML += getText(xml);
      //GRAVITY생성
      viewHTML += getGravity(xml);
      //ELLIPSIZE생성
      viewHTML += getEllipsize(xml);
      //BACKGROUND생성
      viewHTML += getBackground(xml);
      return viewHTML;
   }

**Comment by leedhm88** [comment]
// TextView 속성 추출
   function makeTextView(xml)
   {
      //DIV생성
      var viewHTML = "<div ";
      //ID생성
      viewHTML += getId(xml);
      //DIV STYLE생성
      viewHTML += "style=\"background-color:#FFF;"+defaultOrientation;
      //SPAN 기본 Default View 속성 생성
      viewHTML += makeDefaultView(xml);
      //END STYLE생성
      viewHTML += "\" ";
      //TextView Class 생성
      viewHTML += setClass("TextView");
      //END DIV생성
      viewHTML += ">";
      //SPAN CLASS생성
      viewHTML += "<span>";
      //TEXT생성:텍스트는 가장 마지막에 추가 하고 종료한다.
      viewHTML += getText(xml)+"</span></div>";
      return viewHTML;
   }
